#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3
TOTAL_MINUTES=1

PROJECT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
CHARACTERS_DIR="$PROJECT_DIR/characters"
BUILD_DIR="$PROJECT_DIR/build"

run_helper() {
  if [[ -x "$PROJECT_DIR/.venv/bin/dicethrone-helper" ]]; then
    "$PROJECT_DIR/.venv/bin/dicethrone-helper" "$@"
  elif command -v dicethrone-helper >/dev/null 2>&1; then
    dicethrone-helper "$@"
  else
    PYTHONPATH="$PROJECT_DIR/src" python3 -m dicethrone_helper "$@"
  fi
}

choose_character() {
  local selected=0 key sequence index
  while true; do
    _clear
    printf '\n%s%s▸ Choix du personnage%s\n' "$BOLD" "$BLUE" "$RESET"
    say "Utilisez ↑/↓ puis Entrée pour valider."
    printf '\n'
    for ((index = 0; index < ${#character_names[@]}; index++)); do
      if (( index == selected )); then
        printf '  %s%s› %s%s\n' "$BOLD" "$GREEN" "${character_names[$index]}" "$RESET"
      else
        printf '    %s\n' "${character_names[$index]}"
      fi
    done

    if ! IFS= read -r -s -n 1 key; then
      printf '\n' >&2
      exit 2
    fi
    case "$key" in
      '')
        character_name="${character_names[$selected]}"
        character_file="$CHARACTERS_DIR/$character_name.json"
        return
        ;;
      $'\x1b')
        IFS= read -r -s -n 2 sequence || true
        case "$sequence" in
          '[A'|'OA') selected=$(( (selected - 1 + ${#character_names[@]}) % ${#character_names[@]} )) ;;
          '[B'|'OB') selected=$(( (selected + 1) % ${#character_names[@]} )) ;;
        esac
        ;;
      k) selected=$(( (selected - 1 + ${#character_names[@]}) % ${#character_names[@]} )) ;;
      j) selected=$(( (selected + 1) % ${#character_names[@]} )) ;;
    esac
  done
}

if (( $# > 1 )); then
  printf 'Usage: %s [personnage|--all]\n' "$(basename "$0")" >&2
  exit 2
fi

shopt -s nullglob
character_files=("$CHARACTERS_DIR"/*.json)
shopt -u nullglob
if (( ${#character_files[@]} == 0 )); then
  warn "aucun personnage trouvé dans $CHARACTERS_DIR"
  exit 2
fi

character_names=()
for file in "${character_files[@]}"; do
  name=$(basename "$file")
  character_names+=("${name%.json}")
done

if [[ "${1:-}" == "--all" ]]; then
  mkdir -p "$BUILD_DIR"
  analysis_files=()
  stage "Génération du site" 1
  for character_name in "${character_names[@]}"; do
    character_file="$CHARACTERS_DIR/$character_name.json"
    analysis_file="$BUILD_DIR/$character_name.analysis.json"
    report_file="$BUILD_DIR/$character_name.report.html"
    if [[ ! -f "$analysis_file" || "$analysis_file" -ot "$character_file" ]]; then
      say "$character_name : calcul de l'analyse exacte."
      run_helper analyze "$character_file" --output "$analysis_file"
    else
      say "$character_name : réutilisation de l'analyse à jour."
    fi
    run_helper report "$analysis_file" --output "$report_file"
    analysis_files+=("$analysis_file")
  done

  index_file="$BUILD_DIR/index.html"
  run_helper index "${analysis_files[@]}" --output "$index_file"
  open_url "$index_file"
  finish
  say "Site prêt : $index_file"
  exit 0
fi

stage "Choix du personnage" 0
if (( $# == 1 )); then
  character_name="$1"
  character_file="$CHARACTERS_DIR/$character_name.json"
  if [[ ! -f "$character_file" ]]; then
    warn "personnage inconnu : $character_name"
    say "Personnages disponibles : ${character_names[*]}"
    exit 2
  fi
else
  choose_character
fi
say "Personnage : $character_name"

mkdir -p "$BUILD_DIR"
analysis_file="$BUILD_DIR/$character_name.analysis.json"
report_file="$BUILD_DIR/$character_name.report.html"

stage "Analyse probabiliste" 1
if [[ ! -f "$analysis_file" || "$analysis_file" -ot "$character_file" ]]; then
  say "Le cache est absent ou obsolète : calcul de l'analyse exacte."
  run_helper analyze "$character_file" --output "$analysis_file"
else
  say "Analyse à jour : réutilisation de $analysis_file"
fi

stage "Rapport HTML" 0
say "Génération de $report_file"
run_helper report "$analysis_file" --output "$report_file"
open_url "$report_file"

finish
say "Rapport prêt : $report_file"
